#if defined CONFIG_AHBM_PASSTHRU_1
#define CONFIG_AHBM_PT 1
#elif defined CONFIG_AHBM_PASSTHRU_2
#define CONFIG_AHBM_PT 2
#else
#define CONFIG_AHBM_PT 0
#endif

#if defined CONFIG_AHBS_PASSTHRU_1
#define CONFIG_AHBS_PT 1
#elif defined CONFIG_AHBS_PASSTHRU_2
#define CONFIG_AHBS_PT 2
#elif defined CONFIG_AHBS_PASSTHRU_3
#define CONFIG_AHBS_PT 3
#elif defined CONFIG_AHBS_PASSTHRU_4
#define CONFIG_AHBS_PT 4
#else
#define CONFIG_AHBS_PT 0
#endif


#ifndef CONFIG_AHBM0_BAR0
#define CONFIG_AHBM0_BAR0 000
#endif

#ifndef CONFIG_AHBM0_MASK0
#define CONFIG_AHBM0_MASK0 000
#endif

#ifndef CONFIG_AHBM0_BARTYPE0
#define CONFIG_AHBM0_BARTYPE0 0
#endif

#ifndef CONFIG_AHBM0_PF0
#define CONFIG_AHBM0_PF0 0
#endif

#ifndef CONFIG_AHBM0_CA0
#define CONFIG_AHBM0_CA0 0
#endif

#ifndef CONFIG_AHBM0_BAR1
#define CONFIG_AHBM0_BAR1 000
#endif

#ifndef CONFIG_AHBM0_MASK1
#define CONFIG_AHBM0_MASK1 000
#endif

#ifndef CONFIG_AHBM0_BARTYPE1
#define CONFIG_AHBM0_BARTYPE1 0
#endif

#ifndef CONFIG_AHBM0_PF1
#define CONFIG_AHBM0_PF1 0
#endif

#ifndef CONFIG_AHBM0_CA1
#define CONFIG_AHBM0_CA1 0
#endif

#ifndef CONFIG_AHBM0_BAR2
#define CONFIG_AHBM0_BAR2 000
#endif

#ifndef CONFIG_AHBM0_MASK2
#define CONFIG_AHBM0_MASK2 000
#endif

#ifndef CONFIG_AHBM0_BARTYPE2
#define CONFIG_AHBM0_BARTYPE2 0
#endif

#ifndef CONFIG_AHBM0_PF2
#define CONFIG_AHBM0_PF2 0
#endif

#ifndef CONFIG_AHBM0_CA2
#define CONFIG_AHBM0_CA2 0
#endif

#ifndef CONFIG_AHBM0_BAR3
#define CONFIG_AHBM0_BAR3 000
#endif

#ifndef CONFIG_AHBM0_MASK3
#define CONFIG_AHBM0_MASK3 000
#endif

#ifndef CONFIG_AHBM0_BARTYPE3
#define CONFIG_AHBM0_BARTYPE3 0
#endif

#ifndef CONFIG_AHBM0_PF3
#define CONFIG_AHBM0_PF3 0
#endif

#ifndef CONFIG_AHBM0_CA3
#define CONFIG_AHBM0_CA3 0
#endif

#ifndef CONFIG_AHBM1_BAR0
#define CONFIG_AHBM1_BAR0 000
#endif

#ifndef CONFIG_AHBM1_MASK0
#define CONFIG_AHBM1_MASK0 000
#endif

#ifndef CONFIG_AHBM1_BARTYPE0
#define CONFIG_AHBM1_BARTYPE0 0
#endif

#ifndef CONFIG_AHBM1_PF0
#define CONFIG_AHBM1_PF0 0
#endif

#ifndef CONFIG_AHBM1_CA0
#define CONFIG_AHBM1_CA0 0
#endif

#ifndef CONFIG_AHBM1_BAR1
#define CONFIG_AHBM1_BAR1 000
#endif

#ifndef CONFIG_AHBM1_MASK1
#define CONFIG_AHBM1_MASK1 000
#endif

#ifndef CONFIG_AHBM1_BARTYPE1
#define CONFIG_AHBM1_BARTYPE1 0
#endif

#ifndef CONFIG_AHBM1_PF1
#define CONFIG_AHBM1_PF1 0
#endif

#ifndef CONFIG_AHBM1_CA1
#define CONFIG_AHBM1_CA1 0
#endif

#ifndef CONFIG_AHBM1_BAR2
#define CONFIG_AHBM1_BAR2 000
#endif

#ifndef CONFIG_AHBM1_MASK2
#define CONFIG_AHBM1_MASK2 000
#endif

#ifndef CONFIG_AHBM1_BARTYPE2
#define CONFIG_AHBM1_BARTYPE2 0
#endif

#ifndef CONFIG_AHBM1_PF2
#define CONFIG_AHBM1_PF2 0
#endif

#ifndef CONFIG_AHBM1_CA2
#define CONFIG_AHBM1_CA2 0
#endif

#ifndef CONFIG_AHBM1_BAR3
#define CONFIG_AHBM1_BAR3 000
#endif

#ifndef CONFIG_AHBM1_MASK3
#define CONFIG_AHBM1_MASK3 000
#endif

#ifndef CONFIG_AHBM1_BARTYPE3
#define CONFIG_AHBM1_BARTYPE3 0
#endif

#ifndef CONFIG_AHBM1_PF3
#define CONFIG_AHBM1_PF3 0
#endif

#ifndef CONFIG_AHBM1_CA3
#define CONFIG_AHBM1_CA3 0
#endif

#ifndef CONFIG_AHBS0_BAR0
#define CONFIG_AHBS0_BAR0 000
#endif

#ifndef CONFIG_AHBS0_MASK0
#define CONFIG_AHBS0_MASK0 000
#endif

#ifndef CONFIG_AHBS0_BARTYPE0
#define CONFIG_AHBS0_BARTYPE0 0
#endif

#ifndef CONFIG_AHBS0_PF0
#define CONFIG_AHBS0_PF0 0
#endif

#ifndef CONFIG_AHBS0_CA0
#define CONFIG_AHBS0_CA0 0
#endif

#ifndef CONFIG_AHBS0_BAR1
#define CONFIG_AHBS0_BAR1 000
#endif

#ifndef CONFIG_AHBS0_MASK1
#define CONFIG_AHBS0_MASK1 000
#endif

#ifndef CONFIG_AHBS0_BARTYPE1
#define CONFIG_AHBS0_BARTYPE1 0
#endif

#ifndef CONFIG_AHBS0_PF1
#define CONFIG_AHBS0_PF1 0
#endif

#ifndef CONFIG_AHBS0_CA1
#define CONFIG_AHBS0_CA1 0
#endif

#ifndef CONFIG_AHBS0_BAR2
#define CONFIG_AHBS0_BAR2 000
#endif

#ifndef CONFIG_AHBS0_MASK2
#define CONFIG_AHBS0_MASK2 000
#endif

#ifndef CONFIG_AHBS0_BARTYPE2
#define CONFIG_AHBS0_BARTYPE2 0
#endif

#ifndef CONFIG_AHBS0_PF2
#define CONFIG_AHBS0_PF2 0
#endif

#ifndef CONFIG_AHBS0_CA2
#define CONFIG_AHBS0_CA2 0
#endif

#ifndef CONFIG_AHBS0_BAR3
#define CONFIG_AHBS0_BAR3 000
#endif

#ifndef CONFIG_AHBS0_MASK3
#define CONFIG_AHBS0_MASK3 000
#endif

#ifndef CONFIG_AHBS0_BARTYPE3
#define CONFIG_AHBS0_BARTYPE3 0
#endif

#ifndef CONFIG_AHBS0_PF3
#define CONFIG_AHBS0_PF3 0
#endif

#ifndef CONFIG_AHBS0_CA3
#define CONFIG_AHBS0_CA3 0
#endif

#ifndef CONFIG_AHBS1_BAR0
#define CONFIG_AHBS1_BAR0 000
#endif

#ifndef CONFIG_AHBS1_MASK0
#define CONFIG_AHBS1_MASK0 000
#endif

#ifndef CONFIG_AHBS1_BARTYPE0
#define CONFIG_AHBS1_BARTYPE0 0
#endif

#ifndef CONFIG_AHBS1_PF0
#define CONFIG_AHBS1_PF0 0
#endif

#ifndef CONFIG_AHBS1_CA0
#define CONFIG_AHBS1_CA0 0
#endif

#ifndef CONFIG_AHBS1_BAR1
#define CONFIG_AHBS1_BAR1 000
#endif

#ifndef CONFIG_AHBS1_MASK1
#define CONFIG_AHBS1_MASK1 000
#endif

#ifndef CONFIG_AHBS1_BARTYPE1
#define CONFIG_AHBS1_BARTYPE1 0
#endif

#ifndef CONFIG_AHBS1_PF1
#define CONFIG_AHBS1_PF1 0
#endif

#ifndef CONFIG_AHBS1_CA1
#define CONFIG_AHBS1_CA1 0
#endif

#ifndef CONFIG_AHBS1_BAR2
#define CONFIG_AHBS1_BAR2 000
#endif

#ifndef CONFIG_AHBS1_MASK2
#define CONFIG_AHBS1_MASK2 000
#endif

#ifndef CONFIG_AHBS1_BARTYPE2
#define CONFIG_AHBS1_BARTYPE2 0
#endif

#ifndef CONFIG_AHBS1_PF2
#define CONFIG_AHBS1_PF2 0
#endif

#ifndef CONFIG_AHBS1_CA2
#define CONFIG_AHBS1_CA2 0
#endif

#ifndef CONFIG_AHBS1_BAR3
#define CONFIG_AHBS1_BAR3 000
#endif

#ifndef CONFIG_AHBS1_MASK3
#define CONFIG_AHBS1_MASK3 000
#endif

#ifndef CONFIG_AHBS1_BARTYPE3
#define CONFIG_AHBS1_BARTYPE3 0
#endif

#ifndef CONFIG_AHBS1_PF3
#define CONFIG_AHBS1_PF3 0
#endif

#ifndef CONFIG_AHBS1_CA3
#define CONFIG_AHBS1_CA3 0
#endif

#ifndef CONFIG_AHBS2_BAR0
#define CONFIG_AHBS2_BAR0 000
#endif

#ifndef CONFIG_AHBS2_MASK0
#define CONFIG_AHBS2_MASK0 000
#endif

#ifndef CONFIG_AHBS2_BARTYPE0
#define CONFIG_AHBS2_BARTYPE0 0
#endif

#ifndef CONFIG_AHBS2_PF0
#define CONFIG_AHBS2_PF0 0
#endif

#ifndef CONFIG_AHBS2_CA0
#define CONFIG_AHBS2_CA0 0
#endif

#ifndef CONFIG_AHBS2_BAR1
#define CONFIG_AHBS2_BAR1 000
#endif

#ifndef CONFIG_AHBS2_MASK1
#define CONFIG_AHBS2_MASK1 000
#endif

#ifndef CONFIG_AHBS2_BARTYPE1
#define CONFIG_AHBS2_BARTYPE1 0
#endif

#ifndef CONFIG_AHBS2_PF1
#define CONFIG_AHBS2_PF1 0
#endif

#ifndef CONFIG_AHBS2_CA1
#define CONFIG_AHBS2_CA1 0
#endif

#ifndef CONFIG_AHBS2_BAR2
#define CONFIG_AHBS2_BAR2 000
#endif

#ifndef CONFIG_AHBS2_MASK2
#define CONFIG_AHBS2_MASK2 000
#endif

#ifndef CONFIG_AHBS2_BARTYPE2
#define CONFIG_AHBS2_BARTYPE2 0
#endif

#ifndef CONFIG_AHBS2_PF2
#define CONFIG_AHBS2_PF2 0
#endif

#ifndef CONFIG_AHBS2_CA2
#define CONFIG_AHBS2_CA2 0
#endif

#ifndef CONFIG_AHBS2_BAR3
#define CONFIG_AHBS2_BAR3 000
#endif

#ifndef CONFIG_AHBS2_MASK3
#define CONFIG_AHBS2_MASK3 000
#endif

#ifndef CONFIG_AHBS2_BARTYPE3
#define CONFIG_AHBS2_BARTYPE3 0
#endif

#ifndef CONFIG_AHBS2_PF3
#define CONFIG_AHBS2_PF3 0
#endif

#ifndef CONFIG_AHBS2_CA3
#define CONFIG_AHBS2_CA3 0
#endif

#ifndef CONFIG_AHBS3_BAR0
#define CONFIG_AHBS3_BAR0 000
#endif

#ifndef CONFIG_AHBS3_MASK0
#define CONFIG_AHBS3_MASK0 000
#endif

#ifndef CONFIG_AHBS3_BARTYPE0
#define CONFIG_AHBS3_BARTYPE0 0
#endif

#ifndef CONFIG_AHBS3_PF0
#define CONFIG_AHBS3_PF0 0
#endif

#ifndef CONFIG_AHBS3_CA0
#define CONFIG_AHBS3_CA0 0
#endif

#ifndef CONFIG_AHBS3_BAR1
#define CONFIG_AHBS3_BAR1 000
#endif

#ifndef CONFIG_AHBS3_MASK1
#define CONFIG_AHBS3_MASK1 000
#endif

#ifndef CONFIG_AHBS3_BARTYPE1
#define CONFIG_AHBS3_BARTYPE1 0
#endif

#ifndef CONFIG_AHBS3_PF1
#define CONFIG_AHBS3_PF1 0
#endif

#ifndef CONFIG_AHBS3_CA1
#define CONFIG_AHBS3_CA1 0
#endif

#ifndef CONFIG_AHBS3_BAR2
#define CONFIG_AHBS3_BAR2 000
#endif

#ifndef CONFIG_AHBS3_MASK2
#define CONFIG_AHBS3_MASK2 000
#endif

#ifndef CONFIG_AHBS3_BARTYPE2
#define CONFIG_AHBS3_BARTYPE2 0
#endif

#ifndef CONFIG_AHBS3_PF2
#define CONFIG_AHBS3_PF2 0
#endif

#ifndef CONFIG_AHBS3_CA2
#define CONFIG_AHBS3_CA2 0
#endif

#ifndef CONFIG_AHBS3_BAR3
#define CONFIG_AHBS3_BAR3 000
#endif

#ifndef CONFIG_AHBS3_MASK3
#define CONFIG_AHBS3_MASK3 000
#endif

#ifndef CONFIG_AHBS3_BARTYPE3
#define CONFIG_AHBS3_BARTYPE3 0
#endif

#ifndef CONFIG_AHBS3_PF3
#define CONFIG_AHBS3_PF3 0
#endif

#ifndef CONFIG_AHBS3_CA3
#define CONFIG_AHBS3_CA3 0
#endif
