#ifndef CONFIG_EXTAHB_ENABLE
#define CONFIG_EXTAHB_ENABLE 0
#define CONFIG_EXTAHB_BASE A00
#define CONFIG_EXTAHB_INT 6
#endif

#ifndef CONFIG_SDRAM_SHIFT
#define CONFIG_SDRAM_SHIFT 0
#endif

#ifdef CONFIG_BOOTOPT_INT
#define CONFIG_BOOTOPT 1
#else
#define CONFIG_BOOTOPT 0
#endif

#ifdef CONFIG_HPEVER_1
#define CONFIG_HPEVER 1
#else
#define CONFIG_HPEVER 2
#endif

